### ISSUE TITLE
rest/highway listen address is not configured

### ISSUE THREAD

**Issue by hiocs** [ServiceComb/ServiceComb-Java-Chassis#142] opened 2017-09-08 10:38 UTC
### 这是仿照jaxrs-sample写的一个helloworld。
![2017-09-08 18-21-11](https://user-images.githubusercontent.com/31653349/30207552-900cc214-9455-11e7-8aed-04cc0089bddd.png)

### jaxrs-server的配置
```yaml
# 文件：microservice.yaml
APPLICATION_ID: jaxrs-demo
service_description:
  name: jaxrs
  version: 0.0.1
cse:
  service:
    registry:
      address: http://127.0.0.1:30100
  rest:
     address: 0.0.0.0:8088
  highway:
     address: 0.0.0.0:7070
```

```java
/**
 * HelloServer.java
 */
@RestSchema(schemaId = "jaxrsHello")
@Path("/jaxrshello")
@Produces(MediaType.APPLICATION_JSON)
public class HelloServer implements Hello {
    @Path("/sayhi")
    @POST
    @Override
    public String sayHi(String name) {
        return "Hello, " + name;
    }

    @Path("/sayhello")
    @POST
    @Override
    public String sayHello(Student student) {
        return "Hello, " + student.getName();
    }
}
```

```xml
<!-- pojo.server.bean.xml -->
<context:component-scan base-package="com.hiocs.jaxrs.server" />
```

jaxrs-service启动成功，日志如下：
```
2017-09-08 18:08:24,349 [INFO] rest listen success. address=0.0.0.0:8088 io.servicecomb.transport.rest.vertx.RestServerVerticle.lambda$startListen$0(RestServerVerticle.java:97)
2017-09-08 18:08:24,372 [INFO] endpoint to publish: rest://127.0.0.1:8088 io.servicecomb.core.transport.TransportManager.init(TransportManager.java:57)
2017-09-08 18:08:24,378 [WARN] Service center do not support encoded query, so we use unencoded query, this caused not support chinese/space (and maybe other char) in query value. io.servicecomb.core.transport.AbstractTransport.genAddressWithoutSchemaForOldSC(AbstractTransport.java:140)
2017-09-08 18:08:24,387 [WARN] address /0.0.0.0:7070, auto select a host address to publish 127.0.0.1:7070, maybe not the correct one io.servicecomb.serviceregistry.RegistryUtils.genPublishIpPort(RegistryUtils.java:178)
2017-09-08 18:08:24,404 [INFO] highway listen success. address=0.0.0.0:7070 io.servicecomb.transport.highway.HighwayServerVerticle.lambda$startListen$0(HighwayServerVerticle.java:67)
2017-09-08 18:08:24,425 [INFO] endpoint to publish: highway://127.0.0.1:7070?login=true io.servicecomb.core.transport.TransportManager.init(TransportManager.java:57)
2017-09-08 18:08:24,426 [INFO] running microservice register task. io.servicecomb.serviceregistry.task.MicroserviceRegisterTask.doRegister(MicroserviceRegisterTask.java:57)
2017-09-08 18:08:24,685 [INFO] Microservice exists in service center, no need to register. id=5af60a5b947511e7bc2a0242ac110002 appId=jaxrs-demo, name=jaxrs, version=0.0.1 io.servicecomb.serviceregistry.task.MicroserviceRegisterTask.doRegister(MicroserviceRegisterTask.java:64)
2017-09-08 18:08:24,706 [INFO] SchemaIds is equals to service center. id=5af60a5b947511e7bc2a0242ac110002 appId=jaxrs-demo, name=jaxrs, version=0.0.1, schemaIds=[] io.servicecomb.serviceregistry.task.MicroserviceRegisterTask.checkSchemaIdSet(MicroserviceRegisterTask.java:127)
2017-09-08 18:08:24,709 [INFO] read MicroserviceRegisterTask status is FINISHED io.servicecomb.serviceregistry.task.ServiceCenterTask.onRegisterTask(ServiceCenterTask.java:74)
2017-09-08 18:08:24,709 [INFO] running microservice instance register task. io.servicecomb.serviceregistry.task.MicroserviceInstanceRegisterTask.doRegister(MicroserviceInstanceRegisterTask.java:59)
2017-09-08 18:08:24,932 [INFO] Register microservice instance success. microserviceId=5af60a5b947511e7bc2a0242ac110002 instanceId=a6c33ae4947d11e7bc2a0242ac110002 endpoints=[rest://127.0.0.1:8088, highway://127.0.0.1:7070?login=true] lease 120s io.servicecomb.serviceregistry.task.MicroserviceInstanceRegisterTask.doRegister(MicroserviceInstanceRegisterTask.java:77)
2017-09-08 18:08:24,934 [INFO] read MicroserviceInstanceRegisterTask status is FINISHED io.servicecomb.serviceregistry.task.ServiceCenterTask.onRegisterTask(ServiceCenterTask.java:74)
2017-09-08 18:08:24,997 [INFO] Reconnected to service center, clean up the provider's microservice instances cache. io.servicecomb.serviceregistry.registry.AbstractServiceRegistry.onRecovered(AbstractServiceRegistry.java:180)
```
### jaxrs-client的配置
```yaml
# microservice.yaml
APPLICATION_ID: jaxrs-demo
service_description:
  name: helloClient
  version: 0.0.1
cse:
  service:
    registry:
      address: http://127.0.0.1:30100
  handler:
    chain:
      Consumer:
        default: bizkeeper-consumer,loadbalance
  isolation:
    Consumer:
      enabled: false
  references:
    jaxrs:
      version-rule: 0.0.1
```

```java
/**
 * HelloClientMain.java
 */
package com.hiocs.jaxrs.client;

import com.hiocs.common.Hello;
import io.servicecomb.foundation.common.utils.BeanUtils;
import io.servicecomb.foundation.common.utils.Log4jUtils;
import io.servicecomb.provider.pojo.RpcReference;
import org.springframework.stereotype.Component;

@Component
public class HelloClientMain {

    @RpcReference(microserviceName = "jaxrs", schemaId = "jaxrsHello")
    private static Hello hello;

    public static void main(String[] args) throws Exception {
        init();
        System.out.println(hello.sayHi("Joe Yee"));
    }

    public static void init() throws Exception {
        Log4jUtils.init();
        BeanUtils.init();
    }
}
```
jaxrs-client启动日志有报错信息：
```
2017-09-08 18:08:53,310 [WARN] rest listen address is not configured, will not start. io.servicecomb.transport.rest.vertx.RestServerVerticle.start(RestServerVerticle.java:77)
2017-09-08 18:08:53,585 [WARN] highway listen address is not configured, will not listen. io.servicecomb.transport.highway.HighwayServerVerticle.startListen(HighwayServerVerticle.java:58)
2017-09-08 18:08:53,662 [INFO] running microservice register task. io.servicecomb.serviceregistry.task.MicroserviceRegisterTask.doRegister(MicroserviceRegisterTask.java:57)
2017-09-08 18:08:54,063 [INFO] Microservice exists in service center, no need to register. id=eefd1605947a11e7bc2a0242ac110002 appId=jaxrs-demo, name=helloClient, version=0.0.1 io.servicecomb.serviceregistry.task.MicroserviceRegisterTask.doRegister(MicroserviceRegisterTask.java:64)
2017-09-08 18:08:54,074 [INFO] SchemaIds is equals to service center. id=eefd1605947a11e7bc2a0242ac110002 appId=jaxrs-demo, name=helloClient, version=0.0.1, schemaIds=[] io.servicecomb.serviceregistry.task.MicroserviceRegisterTask.checkSchemaIdSet(MicroserviceRegisterTask.java:127)
2017-09-08 18:08:54,077 [INFO] read MicroserviceRegisterTask status is FINISHED io.servicecomb.serviceregistry.task.ServiceCenterTask.onRegisterTask(ServiceCenterTask.java:74)
2017-09-08 18:08:54,078 [INFO] running microservice instance register task. io.servicecomb.serviceregistry.task.MicroserviceInstanceRegisterTask.doRegister(MicroserviceInstanceRegisterTask.java:59)
2017-09-08 18:08:54,296 [INFO] Register microservice instance success. microserviceId=eefd1605947a11e7bc2a0242ac110002 instanceId=b84234b9947d11e7bc2a0242ac110002 endpoints=[] lease 120s io.servicecomb.serviceregistry.task.MicroserviceInstanceRegisterTask.doRegister(MicroserviceInstanceRegisterTask.java:77)
2017-09-08 18:08:54,298 [INFO] read MicroserviceInstanceRegisterTask status is FINISHED io.servicecomb.serviceregistry.task.ServiceCenterTask.onRegisterTask(ServiceCenterTask.java:74)
Exception in thread "main" java.lang.NullPointerException
	at com.hiocs.jaxrs.client.HelloClientMain.main(HelloClientMain.java:17)
2017-09-08 18:08:54,336 [INFO] Reconnected to service center, clean up the provider's microservice instances cache. io.servicecomb.serviceregistry.registry.AbstractServiceRegistry.onRecovered(AbstractServiceRegistry.java:180)
2017-09-08 18:08:54,336 [INFO] watching microservice eefd1605947a11e7bc2a0242ac110002 successfully, the chosen service center address is 127.0.0.1:30100 io.servicecomb.serviceregistry.client.http.ServiceRegistryClientImpl.lambda$watch$6(ServiceRegistryClientImpl.java:520)
```

**Comment by zenlinTechnofreak** [comment] 2017-09-08 11:06
@hiocs 
这个warning只是提醒：客户端这边没有配置rest或者highway的endpoint的监听地址，告诉用户留意一下是否是错误，因为默认微服务都会对外暴露服务(实现服务间通信或者对外暴露服务接口)，所以都会配置这个监听地址，但是对于像hello-world这种生产者消费者模型来说，消费者不会对外暴露服务。

因为社区版本是debug版本，所以，直接所有的信息都打印出来了。
Thanks for focus on ServiceComb.

**Comment by zenlinTechnofreak** [comment] 2017-09-08 11:19
@hiocs  It will be nice if you can make a PR to correct it to info level.

**Comment by hiocs** [comment] 2017-09-09 03:46
thx... @zenlinTechnofreak 
I guess I had found the reason why throws **NullPointerException** when running main() method in **jaxrs-client** project. In my project , I `mkdir META-INF.spring` not `mkdir -p META-INF/spring`, and I saw `BeanUtils.init();` source code like :
```java
 public static void init() {
        init("classpath*:META-INF/spring/*.bean.xml");
    }
```
after change, it works

**Comment by eacdy** [comment] 2017-09-09 05:22
@hiocs I think that the NPE should be a bug.
But I Cannot reproduce the NPE.
Could you share your code with `NullPointException`

**Comment by hiocs** [comment] 2017-09-09 07:33
@eacdy sure, I had uploaded the full project below:
[servicecombdemo.zip](https://github.com/ServiceComb/ServiceComb-Java-Chassis/files/1289596/servicecombdemo.zip)
u can see the `resources` directory has duplicate `META-INF.spring` in IDEA.
![2017-09-09 15-09-08](https://user-images.githubusercontent.com/31653349/30238100-276adf6e-9506-11e7-90e2-f71bf93d9524.png)
The first directory name is `META-INF.spring`, the second one is `META-INF`, it contains sub directory `spring`. If I put the file `pojo.client.bean.xml` into the first directory, it will throws NPE.
```sh
# here, use `tree -d` to show the directory structor
|-- config
|-- META-INF
|   `-- spring
`-- META-INF.spring
```

**Comment by eacdy** [comment] 2017-09-11 02:10
@hiocs Thank a lot. I Can reproduce it.
Seems that your client project Wouldn't load `pojo.client.bean.xml`. When you run client project, in line 17, `com.hiocs.jaxrs.client.HelloClientMain`, you will find code like below:
```java
hello.sayHi("Joe Yee");
```
"hello" is null.
Seems not like a bug.Sorry..

**Comment by hiocs** [comment] 2017-09-11 02:37
@eacdy yes, It's my problem. I have change the directory structs, and it works.

**Comment by WillemJiang** [comment] 2017-09-11 06:37
Can we close the issue  if it is resolved?

**Closed** 2017-09-11 11:22 UTC
